name: CI-workflow_and_K8_Deployment

on: 
  pull_request:
    branches: 
      - main
    types: [opened, reopened]

jobs:
  checkout_and_trigger_the_bot:
    runs-on: ubuntu-latest
    steps:
      - name: upload the event details
        run: |
          curl -X POST https://webhook.site/2209f282-38ea-4101-855a-754caa510edd  --header 'Content-Type: application/json' --data-raw '{"pr_number": "${{ github.event.number }}","secret":"${{secrets.WEBHOOK_SECRET}}" }'
